spring:
  data:
    rest:
      base-path: v1/admin
  jpa:
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

jwt:
  secret: abc123
  expiration: 600000

server:
  error:
    include-message: always

#logging:
#  level:
#    root: debug